### ISSUE TITLE
Troubleshooting UI

### ISSUE THREAD

**Issue by mjaakko** [mjaakko/NeoStumbler#156]
For optimal scan results, there are several settings that need to be configured. These include:
* Permissions
* Location access / GPS
* Battery optimisations
* Wi-Fi scan throttling

Create an UI where the user can easily see whether their settings are properly configured and, if possible, provide a link to the settings where it can be fixed

**Comment by AtmosphericIgnition** [comment]
Certain privacy focused Android [distros](https://grapheneos.org/features#sensors-permission-toggle) allow the user to disable app's sensor access.
Because of compatibility issues caused by completely blocking access to sensors, these implementations just give the app zeroed values instead. It might be useful if the troubleshooting UI is able to detect that NeoStumbler is receiving zeroed sensor data.

**Comment by AtmosphericIgnition** [comment]
Most likely compass access. Most Android distros do not expose this option to the user, and just grant it automatically. I have heard that this permission sometimes gets imported into projects by third party libraries. Almost every single app on my phone has this permission listed in its manifest.
